feat: 메뉴 영역 CollectionView 추가
ericKwon95/ChickenKiosk pull request #2
Opened 2024-11-26 04:23 UTC by emilyj4482

| 스크린샷 |
| -- |
| <img src="https://github.com/user-attachments/assets/ac7ab20f-a6cf-4928-bd7d-298c3752e7fa" width=300> |

2024-11-26 04:44 UTC, ericKwon95 approved these changes

2024-11-26 04:46 UTC, ericKwon95 requested changes
수정해주세요!

2024-11-26 04:46 UTC, ericKwon95 commented on ChickenKiosk/CollectionView/ChickenCell.swift
> +class ChickenCell: UICollectionViewCell {
리뷰입니다

2024-11-26 04:46 UTC, ericKwon95 commented on ChickenKiosk/CollectionView/ChickenCell.swift
> +    required init?(coder: NSCoder) {
좋네요

2024-11-26 04:47 UTC, sy0201 commented on ChickenKiosk/Assets.xcassets/honeyBoneless.imageset/Contents.json
> +{
JSON파일까지..! 멋지십니다!

2024-11-26 04:51 UTC, sy0201 commented on ChickenKiosk/ViewController.swift
> +        collectionView.snp.makeConstraints {
저희 나중에 Snapkit 작성하는것도 통일하면 좋겠네요!

2024-11-26 04:51 UTC, sy0201 approved these changes

2024-11-26 09:09 UTC, emilyj4482 commented on ChickenKiosk/ViewController.swift
> +        collectionView.snp.makeConstraints {
네! 그럼 이런 부분은 코딩 컨벤션에 들어가는 거죠?

2024-11-26 09:28 UTC, sy0201 commented on ChickenKiosk/ViewController.swift
> +        collectionView.snp.makeConstraints {
아하! 코딩컨벤션 맞는거같아요!

2024-11-26 10:35 UTC, ericKwon95 approved these changes

2024-11-27 02:40 UTC, daydreamplace approved these changes

2024-11-27 02:40 UTC, daydreamplace commented on ChickenKiosk/Assets.xcassets/redBoneless.imageset/redBoneless.png
맛있겠다

2024-11-27 02:40 UTC, daydreamplace commented on ChickenKiosk/ViewController.swift
> +        collectionView.snp.makeConstraints {
참고하겠습니다!

2024-11-27 02:44 UTC, merged

2024-11-27 10:03 UTC, ericKwon95 commented on ChickenKiosk/CollectionView/ChickenCell.swift
> +    func bind(_ chicken: MockChicken) {
모델과 뷰를 연결지어준다는 의미로 bind 함수명을 작성해 주셨군요~
추후 접할 리액티브 프로그래밍에서 bind라는 함수는 일반적으로 양방향 바인딩을 암시하기 때문에 set , configure 등의 함수명이 조금 더 적절할 수도 있을 것 같아요!

2024-11-27 10:03 UTC, ericKwon95 commented on ChickenKiosk/CollectionView/ChickenCollectionView.swift
> +    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
레이아웃 작성은 처음 접해보셨을텐데 고생 많으셨습니다!

2024-12-07 15:01 UTC, emilyj4482 commented on ChickenKiosk/CollectionView/ChickenCell.swift
> +    func bind(_ chicken: MockChicken) {
조언 감사합니다☺️ 코딩 컨벤션 정하는 시간이 없었던 게 너무 아쉬워요 더 많은 걸 깨달을 수 있었을텐데..

2024-12-08 04:08 UTC, sy0201 commented on ChickenKiosk/CollectionView/ChickenCell.swift
> +    func bind(_ chicken: MockChicken) {
아하! 진짜 함수명 변수명 정하는게 중요한걸 다시한번 알게되었어요! 감사합니다~!